#!/bin/sh

# adjust screen size and touch depending on device model
#
# should in the future be based on the device tree file name because that uniquely defines a device
# /proc/device-tree/model and /proc/device-tree/name

MUX=$(expr "$(cat /proc/cmdline)" : ".*mux=\([^ ]*\)")
[ "$MUX" ] || MUX=$(cat /proc/device-tree/model 2>/dev/null)

case "$MUX$DT" in
	*BeagleBoardB1* )	# OpenmokoBeagleHybrid (with TPO LCD conneced to J4&5)
		cp /etc/X11/xorg.conf.gta04 /etc/X11/xorg.conf
		;;
	*GTA04A2* | *GTA04A3* | *GTA04A4* | *GTA04A5* | *GTA04A3+* | *Letux2804* )	# Letux 2804
		cp /etc/X11/xorg.conf.gta04 /etc/X11/xorg.conf
		;;
	*BeagleBoardB2* | *GTA04B2* | *GTA04B6* | *Letux3704* )	# Letux 3704
		(
		cd /root
		[ -x blanviewd ] || make blanviewd
		./blanviewd &
		)
		cp /etc/X11/xorg.conf.gta04b2 /etc/X11/xorg.conf
		;;
	*BeagleBoardB3* | *GTA04B3* | *Letux7004* )	# Letux 7004
		cp /etc/X11/xorg.conf.gta04b3 /etc/X11/xorg.conf
		;;
	*BeagleBoardB4* | *GTA04B4* )	# Letux 5004
		cp /etc/X11/xorg.conf.gta04b4 /etc/X11/xorg.conf
		;;
	*BeagleBoardB4* | *GTA04B7* | *Neo900* )	# Neo900
		cp /etc/X11/xorg.conf.gta04b7 /etc/X11/xorg.conf
		;;
	*GTA04B8* )	# Letux 2204
		cp /etc/X11/xorg.conf.gta04b8 /etc/X11/xorg.conf
		;;
	*PandaBoard* )
		cp /etc/X11/xorg.conf /etc/X11/xorg.conf
		;;
	Pyra-Handheld )
		cp /etc/X11/xorg.conf.pyra /etc/X11/xorg.conf
		/root/bl 1
		;;
	*Pandora* )
		cp /etc/X11/xorg.conf.pandora /etc/X11/xorg.conf
		;;
	*BeagleBoneBlack* )	# BBB with 4. inch panel cape
		cp /etc/X11/xorg.conf.bbb /etc/X11/xorg.conf
		;;
	* )
		echo "unknown motherboard $MUX"
		echo "we don't know how to configure X11 for the display"
		;;
esac

# exec /usr/bin/X -nolisten tcp "$@"
# allow to access X11 thorough TCP
exec /usr/bin/X "$@"
